[project]
name = "comicfuryscraper"
version = "1.0.1"
description = "A simple terminal CLI app to download ComicFury comics"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{name = "enzomtpYT", email = "contact@enzomtp.party"}]
dependencies = [
    "requests",
    "beautifulsoup4"
]
urls = {repository = "https://github.com/enzomtpYT/ComicFury-AutoCBZ"}
keywords = [
    "python",
    "scraper",
    "downloader",
    "download",
    "images",
    "comic",
    "comics",
    "batch", 
    "comic-downloader",
    "scrape",
    "bulk",
    "cbz",
    "comic-scraper",
    "comicfury",
    "comicpress"
]

[project.scripts]
comicfuryscraper = "comicfuryscraper.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["comicfuryscraper"]
package-dir = {"comicfuryscraper" = "src"}
